-- internal/migrations/001_create_tables.sql

-- Типы транспортных средств
CREATE TABLE vehicle_types (
    id SERIAL PRIMARY KEY,
    name VARCHAR(32) NOT NULL UNIQUE
);

INSERT INTO vehicle_types (name) VALUES
    ('Car'),
    ('Motorcycle');

-- Типы топлива
CREATE TABLE fuel_types (
    id SERIAL PRIMARY KEY,
    name VARCHAR(32) NOT NULL UNIQUE
);

INSERT INTO fuel_types (id, name) VALUES
    (1, 'Petrol'),
    (2, 'PetrolPropaneButane'),
    (3, 'PetrolMethane'),
    (4, 'PetrolHybrid'),
    (5, 'Diesel'),
    (6, 'DieselHybrid'),
    (7, 'Electric');

-- Бренды авто
CREATE TABLE brands (
    id SERIAL PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    vehicle_type_id INT NOT NULL REFERENCES vehicle_types(id),
    UNIQUE(name, vehicle_type_id)
);

INSERT INTO brands (name, vehicle_type_id) VALUES
    ('Abarth', 1),
    ('AC', 1),
    ('Acura', 1),
    ('Adler', 1),
    ('Aito', 1),
    ('Aiways', 1),
    ('Aixam', 1),
    ('Alfa Romeo', 1),
    ('Alpina', 1),
    ('Alpine', 1),
    ('Ambertruck', 1),
    ('AMC', 1),
    ('Arcfox', 1),
    ('Aro', 1),
    ('Asia', 1),
    ('Aston Martin', 1),
    ('Aurus', 1),
    ('Austin', 1),
    ('Autobianchi', 1),
    ('Avatr', 1),
    ('BAIC', 1),
    ('Bajaj', 1),
    ('Baltijas Dzips', 1),
    ('Baojun', 1),
    ('BAW', 1),
    ('Belgee', 1),
    ('Bentley', 1),
    ('Bestune', 1),
    ('Borgward', 1),
    ('Brilliance', 1),
    ('Bugatti', 1),
    ('Buick', 1),
    ('BYD', 1),
    ('Cadillac', 1),
    ('Chana', 1),
    ('Changan', 1),
    ('Changfeng', 1),
    ('Changhe', 1),
    ('Chevrolet', 1),
    ('Chrysler', 1),
    ('Ciimo (Dongfeng-Honda)', 1),
    ('Citroen', 1),
    ('Coda', 1),
    ('Cupra', 1),
    ('Dacia', 1),
    ('Dadi', 1),
    ('Daewoo', 1),
    ('Daihatsu', 1),
    ('Daimler', 1),
    ('Datsun', 1),
    ('Dayun', 1),
    ('Delage', 1),
    ('Denza', 1),
    ('Derways', 1),
    ('Dodge', 1),
    ('Dongfeng', 1),
    ('Doninvest', 1),
    ('Donkervoort', 1),
    ('DS', 1),
    ('DW Hower', 1),
    ('Eagle', 1),
    ('Enovate (Enoreve)', 1),
    ('Everus', 1),
    ('Evolute', 1),
    ('Excalibur', 1),
    ('Exeed', 1),
    ('Facel Vega', 1),
    ('FAW', 1),
    ('Ferrari', 1),
    ('Fiat', 1),
    ('Fisker', 1),
    ('Forthing', 1),
    ('Foton', 1),
    ('FSO', 1),
    ('FSR', 1),
    ('GAC', 1),
    ('GAC Aion', 1),
    ('GAC Trumpchi', 1),
    ('Genesis', 1),
    ('Geo', 1),
    ('GMC', 1),
    ('Great Wall', 1),
    ('Hafei', 1),
    ('Haima', 1),
    ('Hanteng', 1),
    ('Haval', 1),
    ('Hawtai', 1),
    ('Hennessey', 1),
    ('HiPhi', 1),
    ('Honda', 1),
    ('Hongqi', 1),
    ('Hozon', 1),
    ('Hudson', 1),
    ('Hummer', 1),
    ('iCar', 1),
    ('IM Motors (Zhiji)', 1),
    ('Ineos', 1),
    ('Infiniti', 1),
    ('Innocenti', 1),
    ('International Harvester', 1),
    ('Iran Khodro', 1),
    ('Isuzu', 1),
    ('JAC', 1),
    ('Jaecoo', 1),
    ('Jaguar', 1),
    ('Jeep', 1),
    ('Jetour', 1),
    ('Jetta', 1),
    ('Jidu', 1),
    ('Jinbei', 1),
    ('JMC', 1),
    ('Kaiyi', 1),
    ('Kawei', 1),
    ('KGM', 1),
    ('Knewstar', 1),
    ('Koenigsegg', 1),
    ('KTM AG', 1),
    ('Lamborghini', 1),
    ('Lancia', 1),
    ('Land Rover', 1),
    ('Landwind', 1),
    ('Leapmotor', 1),
    ('LEVC', 1),
    ('Lexus', 1),
    ('Liebao Motor', 1),
    ('Lifan', 1),
    ('Lincoln', 1),
    ('Lingxi', 1),
    ('Livan', 1),
    ('LiXiang', 1),
    ('Lotus', 1),
    ('Lucid', 1),
    ('Luxeed', 1),
    ('Luxgen', 1),
    ('Lynk & Co', 1),
    ('M-Hero', 1),
    ('Maextro', 1),
    ('Mahindra', 1),
    ('Maple', 1),
    ('Marussia', 1),
    ('Maserati', 1),
    ('Maxus', 1),
    ('Maybach', 1),
    ('Mazda', 1),
    ('McLaren', 1),
    ('Mercury', 1),
    ('Metrocab', 1),
    ('MG', 1),
    ('Mini', 1),
    ('Mitsubishi', 1),
    ('Mitsuoka', 1),
    ('Morgan', 1),
    ('Nevo', 1),
    ('Nio', 1),
    ('Oldsmobile', 1),
    ('Omoda', 1),
    ('Opel', 1),
    ('Ora', 1),
    ('Oshan', 1),
    ('Oting', 1),
    ('Packard', 1),
    ('Pagani', 1),
    ('Peugeot', 1),
    ('Plymouth', 1),
    ('Polar Stone (Jishi)', 1),
    ('Polestar', 1),
    ('Pontiac', 1),
    ('Porsche', 1),
    ('Proton', 1),
    ('Puch', 1),
    ('Qingling', 1),
    ('Ram', 1),
    ('Ravon', 1),
    ('Reliant', 1),
    ('Renault', 1),
    ('Renault Samsung', 1),
    ('Rising Auto', 1),
    ('Rivian', 1),
    ('Roewe', 1),
    ('Rolls-Royce', 1),
    ('Rover', 1),
    ('Rox', 1),
    ('Saab', 1),
    ('Santana', 1),
    ('Saturn', 1),
    ('Scion', 1),
    ('SEAT', 1),
    ('Seres', 1),
    ('ShuangHuan', 1),
    ('Simca', 1),
    ('Skoda', 1),
    ('Skywell', 1),
    ('Smart', 1),
    ('Solaris', 1),
    ('Sollers', 1),
    ('Soueast', 1),
    ('SsangYong', 1),
    ('Stelato', 1),
    ('Steyr', 1),
    ('Subaru', 1),
    ('Suzuki', 1),
    ('SWM', 1),
    ('Tank', 1),
    ('Tata', 1),
    ('Tatra', 1),
    ('Tesla', 1),
    ('Tianma', 1),
    ('Tianye', 1),
    ('Trabant', 1),
    ('TVR', 1),
    ('Vauxhall', 1),
    ('Venucia', 1),
    ('VGV', 1),
    ('Volkswagen', 1),
    ('Автокам', 1),
    ('Амберавто', 1),
    ('ГАЗ', 1),
    ('Иж', 1),
    ('Канонир', 1),
    ('ЛуАЗ', 1),
    ('Москвич', 1),
    ('СМЗ', 1),
    ('ТагАЗ', 1),
    ('УАЗ', 1)
;

INSERT INTO brands (name, vehicle_type_id) VALUES
    ('Aermacchi', 2),
    ('AJP', 2),
    ('Alfer', 2),
    ('Amazonas', 2),
    ('American Eagle', 2),
    ('American IronHorse', 2),
    ('Anaig', 2),
    ('Apollo', 2),
    ('Aprilia', 2),
    ('Ardie', 2),
    ('Armada', 2),
    ('Aston Martin', 2),
    ('Ataki', 2),
    ('ATK', 2),
    ('Avantis', 2),
    ('Bajaj', 2),
    ('Baltmotors', 2),
    ('Bamx', 2),
    ('Bars', 2),
    ('Bashan', 2),
    ('Benda', 2),
    ('Benelli', 2),
    ('Beta', 2),
    ('Bianchi', 2),
    ('Bifei', 2),
    ('Big Bear Choppers', 2),
    ('Big Dog Motorcycles', 2),
    ('Blata', 2),
    ('Boom Trikes', 2),
    ('Boss Hoss', 2),
    ('Brabus', 2),
    ('BRP', 2),
    ('BRZ', 2),
    ('BSA', 2),
    ('BSE', 2),
    ('Buell', 2),
    ('Cagiva', 2),
    ('Carver', 2),
    ('CCM', 2),
    ('Centurion', 2),
    ('CFMoto', 2),
    ('CH Racing', 2),
    ('Chang-Jiang', 2),
    ('Cobra', 2),
    ('CPI', 2),
    ('CR & S', 2),
    ('Cronus', 2),
    ('CRZ', 2),
    ('Curtiss', 2),
    ('Cyclone', 2),
    ('CZ', 2),
    ('Darex', 2),
    ('Dayun', 2),
    ('Deller', 2),
    ('Derbi', 2),
    ('Desert Raven', 2),
    ('Draxter', 2),
    ('Energica', 2),
    ('Eurotex', 2),
    ('EVA', 2),
    ('Expert Moto', 2),
    ('Falcon', 2),
    ('Fidelis et Fortis', 2),
    ('Fighter', 2),
    ('Forsage', 2),
    ('Fosti', 2),
    ('Fuego', 2),
    ('Full Crew', 2),
    ('Futong', 2),
    ('FXmoto', 2),
    ('Gmax', 2),
    ('Gaokin', 2),
    ('GasGas', 2),
    ('Geon', 2),
    ('Gilera', 2),
    ('GR', 2),
    ('Groza', 2),
    ('Gryphon', 2),
    ('GXmoto', 2),
    ('Hasky', 2),
    ('Hero', 2),
    ('Highland', 2),
    ('Horwin', 2),
    ('Huangpeng', 2),
    ('Husaberg', 2),
    ('Husqvarna', 2),
    ('Hyosung', 2),
    ('Indian', 2),
    ('Irbis', 2),
    ('Iride', 2),
    ('Italian Volt', 2),
    ('Jawa', 2),
    ('JHL', 2),
    ('Jiangsu Sunhou', 2),
    ('JMC', 2),
    ('Johnny Pag', 2),
    ('Jose', 2),
    ('K2R', 2),
    ('Keeway', 2),
    ('Kews', 2),
    ('Kinlon Motors', 2),
    ('Koshine', 2),
    ('Kove', 2),
    ('KXD', 2),
    ('Kymco', 2),
    ('Lem', 2),
    ('Lifan', 2),
    ('Lito', 2),
    ('Loncin', 2),
    ('Magni', 2),
    ('Mikilon', 2),
    ('Minsk', 2),
    ('Montesa', 2),
    ('Motax', 2),
    ('Moto Guzzi', 2),
    ('Moto Morini', 2),
    ('Mowgli', 2),
    ('MV Agusta', 2),
    ('MZ', 2),
    ('Nexus', 2),
    ('Nicot', 2),
    ('Nitro', 2),
    ('NIU', 2),
    ('Norton', 2),
    ('Ohvale', 2),
    ('Omaks', 2),
    ('Orange County Choppers', 2),
    ('Orion', 2),
    ('Oxo', 2),
    ('Pannonia', 2),
    ('Patron', 2),
    ('Pitrace', 2),
    ('Pitster Pro', 2),
    ('Polaris', 2),
    ('Polini', 2),
    ('Procida', 2),
    ('Progasi', 2),
    ('Promax', 2),
    ('PWR Racing', 2),
    ('QJ Motor', 2),
    ('Racer', 2),
    ('Regal Raptor', 2),
    ('Regul Moto', 2),
    ('Rewaco', 2),
    ('Rhino', 2),
    ('Rieju', 2),
    ('Rmoto', 2),
    ('Rockot', 2),
    ('Roliz', 2),
    ('Royal Enfield', 2),
    ('S2 Motors', 2),
    ('Sachs', 2),
    ('Sagitta', 2),
    ('Saxon', 2),
    ('Scanmoto', 2),
    ('Scorpa', 2),
    ('Sharmax', 2),
    ('Sherco', 2),
    ('Shineray', 2),
    ('Simargl Elektro', 2),
    ('Simson', 2),
    ('Skygo', 2),
    ('Sonik', 2),
    ('SPR', 2),
    ('SSSR', 2),
    ('Stark', 2),
    ('Stels', 2),
    ('Stingray', 2),
    ('Super Soco', 2),
    ('Sur-Ron', 2),
    ('Swift', 2),
    ('SWM', 2),
    ('SYM', 2),
    ('Tacita', 2),
    ('Talaria', 2),
    ('Tao Motor', 2),
    ('Tinbot', 2),
    ('Titan', 2),
    ('TM Racing', 2),
    ('TMBK', 2),
    ('Triumph', 2),
    ('TRRS', 2),
    ('TVS', 2),
    ('UM', 2),
    ('Upbeat', 2),
    ('Vanderhall', 2),
    ('Vertigo', 2),
    ('Victory', 2),
    ('Vinto', 2),
    ('Viper', 2),
    ('VMC', 2),
    ('Voge', 2),
    ('Voxan', 2),
    ('Wanderer', 2),
    ('Wanqiang', 2),
    ('Wels', 2),
    ('White Siberia', 2),
    ('Wuxi', 2),
    ('XGZ', 2),
    ('Xingyue', 2),
    ('Xmotos', 2),
    ('Yacota', 2),
    ('Yamasaki', 2),
    ('Yangtze', 2),
    ('YCF', 2),
    ('Yinxiang', 2),
    ('Zero', 2),
    ('ZIP Motors', 2),
    ('ZM', 2),
    ('Zongshen', 2),
    ('Zontes', 2),
    ('Zundapp', 2),
    ('Zuum', 2),
    ('Zuumav', 2),
    ('Гюрза', 2),
    ('Днепр', 2),
    ('ЗиД', 2),
    ('ИЖ', 2),
    ('ИжТехМаш', 2),
    ('Ковровец', 2),
    ('Львовский мотозавод', 2),
    ('ММЗ', 2),
    ('Мотоальфа', 2),
    ('Мотомир', 2),
    ('ПМЗ', 2),
    ('РМЗ', 2),
    ('ТМЗ (Туламашзавод)', 2),
    ('Урал', 2);

-- Типы кузова
CREATE TABLE body_types (
    id SERIAL PRIMARY KEY,
    name VARCHAR(32) NOT NULL,
    parent_id INT REFERENCES body_types(id)
);

INSERT INTO body_types (id, name, parent_id) VALUES
    (1, 'Седан', NULL),
    (2, 'Хэтчбек', NULL),
    (3, 'Хэтчбек 3 дв.', 2),
    (4, 'Хэтчбек 5 дв.', 2),
    (5, 'Лифтбек', 2),
    (6, 'Внедорожник', NULL),
    (7, 'Внедорожник 3 дв.', 6),
    (8, 'Внедорожник 5 дв.', 6),
    (9, 'Универсал', NULL),
    (10, 'Купе', NULL),
    (11, 'Минивэн', NULL),
    (12, 'Пикап', NULL),
    (13, 'Лимузин', NULL),
    (14, 'Фургон', NULL),
    (15, 'Кабриолет', NULL);

-- Типы привода
CREATE TABLE drive_types (
    id SERIAL PRIMARY KEY,
    name VARCHAR(32) NOT NULL,
    parent_id INT REFERENCES drive_types(id)
);

INSERT INTO drive_types (id, name, parent_id) VALUES
    (1, 'Передний', NULL),
    (2, 'Задний', NULL),
    (3, 'Полный', NULL),
    (4, 'Постоянный полный', 3),
    (5, 'Подключаемый полный', 3);

-- Типы трансмиссии
CREATE TABLE transmission_types (
    id SERIAL PRIMARY KEY,
    name VARCHAR(32) NOT NULL,
    parent_id INT REFERENCES transmission_types(id)
);

INSERT INTO transmission_types (id, name, parent_id) VALUES
    (1, 'Автомат', NULL),
    (2, 'Автоматическая', 1),
    (3, 'Робот', 1),
    (4, 'Вариатор', 1),
    (5, 'Механическая', NULL);

-- Категории мотоциклов
CREATE TABLE moto_categories (
    id SERIAL PRIMARY KEY,
    name VARCHAR(32) NOT NULL,
    parent_id INT REFERENCES moto_categories(id)
);

INSERT INTO moto_categories (id, name, parent_id) VALUES
    (1, 'Внедорожные', NULL),
    (2, 'Дорожные', NULL),
    (3, 'Круизеры/Чопперы', NULL),
    (4, 'Спортивные', NULL),
    (5, 'Супермото', NULL),
    (6, 'Трайки', NULL),
    (7, 'Туристические', NULL),
    (8, 'Allround', 1),
    (9, 'Внедорожный Эндуро', 1),
    (10, 'Мотоцикл повышенной проходимости', 1),
    (11, 'Спортивный Эндуро', 1),
    (12, 'Туристический Эндуро', 1),
    (13, 'Naked bike', 2),
    (14, 'Дорожный', 2),
    (15, 'Классик', 2),
    (16, 'Кастом', 3),
    (17, 'Круизер', 3),
    (18, 'Чоппер', 3),
    (19, 'Кросс', 4),
    (20, 'Speedway', 4),
    (21, 'Детский', 4),
    (22, 'Минибайк', 4),
    (23, 'Питбайк', 4),
    (24, 'Триал', 4),
    (25, 'Спорт-байк', 4),
    (26, 'Спорт-туризм', 4),
    (27, 'Супер-спорт', 4),
    (28, 'Трайк', 6),
    (29, 'Трицикл', 6);

-- Категории расходов
CREATE TABLE expense_categories (
    id SERIAL PRIMARY KEY,
    name VARCHAR(32) NOT NULL UNIQUE
);

INSERT INTO expense_categories (name) VALUES
    ('Fuel'),
    ('Repair'),
    ('Maintenance'),
    ('Insurance'),
    ('Taxes'),
    ('Other');

-- Пользователи
CREATE TABLE users (
    id UUID PRIMARY KEY,
    login VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_by UUID,
    created_at_utc TIMESTAMP,
    modified_by UUID,
    modified_at_utc TIMESTAMP
);

-- Автомобили
CREATE TABLE cars (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    fuel_type_id INT NOT NULL REFERENCES fuel_types(id),
    vehicle_type_id INT NOT NULL REFERENCES vehicle_types(id),
    year INT NOT NULL,
    plate VARCHAR(32) NOT NULL,
    vin VARCHAR(64),
    brand_id INT NOT NULL REFERENCES brands(id),
    drive_type_id INT NOT NULL REFERENCES drive_types(id),
    body_type_id INT NOT NULL REFERENCES body_types(id),
    transmission_type_id INT NOT NULL REFERENCES transmission_types(id),
    created_by UUID,
    created_at_utc TIMESTAMP,
    modified_by UUID,
    modified_at_utc TIMESTAMP
);

-- Мотоциклы
CREATE TABLE motos (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    fuel_type_id INT NOT NULL REFERENCES fuel_types(id),
    vehicle_type_id INT NOT NULL REFERENCES vehicle_types(id),
    year INT NOT NULL,
    plate VARCHAR(32) NOT NULL,
    vin VARCHAR(64),
    brand_id INT NOT NULL REFERENCES brands(id),
    category_id INT NOT NULL REFERENCES moto_categories(id),
    transmission_type_id INT NOT NULL REFERENCES transmission_types(id),
    created_by UUID,
    created_at_utc TIMESTAMP,
    modified_by UUID,
    modified_at_utc TIMESTAMP
);

-- Расходы
CREATE TABLE expenses (
    id UUID PRIMARY KEY,
    vehicle_type_id INT NOT NULL REFERENCES vehicle_types(id),
    vehicle_id UUID NOT NULL,
    category_id INT NOT NULL REFERENCES expense_categories(id),
    amount NUMERIC(12,2) NOT NULL,
    currency VARCHAR(8) NOT NULL,
    exchange_rate NUMERIC(12,6) NOT NULL,
    date TIMESTAMP NOT NULL,
    note TEXT,
    created_by UUID,
    created_at_utc TIMESTAMP,
    modified_by UUID,
    modified_at_utc TIMESTAMP,
    FOREIGN KEY (vehicle_id) REFERENCES cars(id) ON DELETE CASCADE
);