server:
  port: 8080
sqlDatabase:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  name: mycar
  sslmode: disable
  maxIdleConns: 10
  maxOpenConns: 50
  connMaxLifetime: 300
noSqlDatabase:
  uri: "mongodb://mongo:27017/mycar"
app:
  secret: "salt1234%"
  tokenTtlHours: 5